name: Jekyll site CI

on:
  push:
    branches: [ "frst_webapp1.0" ]
  pull_request:
    branches: [ "frst_webapp1.0" ]

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: ${{matrix.os}}
    #strategy:
     # matrix:
      #  os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
   
    - name: push the project to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: pravallika1296/devops_learn
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
